// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0YhuArSaSaDE2rtW_oQOhrfkcdKOUlKs',
    appId: '1:89920451985:web:c2b992729d6d9a38759630',
    messagingSenderId: '89920451985',
    projectId: 'flutter-auth-ad4f4',
    authDomain: 'flutter-auth-ad4f4.firebaseapp.com',
    storageBucket: 'flutter-auth-ad4f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiIlGeh4-BGYswCxT2800zgcrI_f93vOs',
    appId: '1:89920451985:android:d30ee7bbc863900a759630',
    messagingSenderId: '89920451985',
    projectId: 'flutter-auth-ad4f4',
    storageBucket: 'flutter-auth-ad4f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFF4D3m2jCqBmH2xYOQZdZ5-jI8-2bOXY',
    appId: '1:89920451985:ios:93d9d833c9b956f7759630',
    messagingSenderId: '89920451985',
    projectId: 'flutter-auth-ad4f4',
    storageBucket: 'flutter-auth-ad4f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFF4D3m2jCqBmH2xYOQZdZ5-jI8-2bOXY',
    appId: '1:89920451985:ios:93d9d833c9b956f7759630',
    messagingSenderId: '89920451985',
    projectId: 'flutter-auth-ad4f4',
    storageBucket: 'flutter-auth-ad4f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0YhuArSaSaDE2rtW_oQOhrfkcdKOUlKs',
    appId: '1:89920451985:web:e6e385ca4a4077a8759630',
    messagingSenderId: '89920451985',
    projectId: 'flutter-auth-ad4f4',
    authDomain: 'flutter-auth-ad4f4.firebaseapp.com',
    storageBucket: 'flutter-auth-ad4f4.firebasestorage.app',
  );
}
