// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaQEkuhMPuhRAZfqKzSww7pA0LewhfPw4',
    appId: '1:1020819824928:web:6b6c5bac97213ef2477745',
    messagingSenderId: '1020819824928',
    projectId: 'natthawanpp',
    authDomain: 'natthawanpp.firebaseapp.com',
    storageBucket: 'natthawanpp.firebasestorage.app',
    measurementId: 'G-KVJEELLBFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_VbcuYpqdaPJH7cD68Dg6DckZ48jWgmM',
    appId: '1:1020819824928:android:f3128e58a8d8ea1c477745',
    messagingSenderId: '1020819824928',
    projectId: 'natthawanpp',
    storageBucket: 'natthawanpp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBMJ39GqfJTY8O-u5vurGYWwAjG1vGPKE',
    appId: '1:1020819824928:ios:c87629938e977a29477745',
    messagingSenderId: '1020819824928',
    projectId: 'natthawanpp',
    storageBucket: 'natthawanpp.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBMJ39GqfJTY8O-u5vurGYWwAjG1vGPKE',
    appId: '1:1020819824928:ios:c87629938e977a29477745',
    messagingSenderId: '1020819824928',
    projectId: 'natthawanpp',
    storageBucket: 'natthawanpp.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaQEkuhMPuhRAZfqKzSww7pA0LewhfPw4',
    appId: '1:1020819824928:web:a8543bc3e9b436a8477745',
    messagingSenderId: '1020819824928',
    projectId: 'natthawanpp',
    authDomain: 'natthawanpp.firebaseapp.com',
    storageBucket: 'natthawanpp.firebasestorage.app',
    measurementId: 'G-NX67LZ1M4Z',
  );

}